# This file is auto-generated by JReleaser
class {{brewFormulaName}} < Formula
  desc "{{projectDescription}}"
  homepage "{{projectLinkHomepage}}"
  url "{{distributionUrl}}"
  sha256 "{{distributionChecksumSha256}}"
  license "{{projectLicense}}"

  depends_on "openjdk@21"

  def install
    libexec.install "nodelhost.jar" => "nodel.jar"

    # Create wrapper script that handles stdin requirement
    # Nodel waits for stdin EOF to shutdown, so we pipe tail in service mode
    (bin/"nodel").write <<~EOS
      #!/bin/bash
      export JAVA_HOME="#{Formula["openjdk@21"].opt_prefix}"
      NODEL_HOME="#{var}/nodel"

      # Ensure data directory exists
      mkdir -p "$NODEL_HOME"
      cd "$NODEL_HOME"

      if [ -t 0 ]; then
        # Interactive mode - stdin is a terminal
        exec "$JAVA_HOME/bin/java" -jar "#{libexec}/nodel.jar" "$@"
      else
        # Service/background mode - keep stdin open
        exec tail -f /dev/null | "$JAVA_HOME/bin/java" -jar "#{libexec}/nodel.jar" "$@"
      fi
    EOS
  end

  def post_install
    (var/"nodel"/"nodes").mkpath
  end

  def caveats
    <<~EOS
      Nodel data is stored in:
        #{var}/nodel

      To start nodel now and restart at login:
        brew services start nodel

      Or run in foreground:
        nodel

      Web interface: http://localhost:8085
    EOS
  end

  service do
    run [opt_bin/"nodel", "-p", "8085"]
    keep_alive true
    working_dir var/"nodel"
    log_path var/"log/nodel.log"
    error_log_path var/"log/nodel-error.log"
  end

  test do
    assert_predicate libexec/"nodel.jar", :exist?
  end
end
